"""
Seed the case_knowledge.db with 75+ famous solved Indian criminal cases.
All cases are publicly documented court records, news archives, and official reports.
Run: python scripts/seed_case_knowledge.py
"""

import json
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "case_knowledge.db"

SCHEMA = """
CREATE TABLE IF NOT EXISTS solved_cases (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    title         TEXT NOT NULL,
    year          INTEGER,
    location      TEXT,
    state         TEXT,
    crime_type    TEXT,
    victim        TEXT,
    accused       TEXT,
    modus_operandi TEXT,
    key_evidence  TEXT,   -- JSON list of evidence items
    how_solved    TEXT,
    breakthrough  TEXT,   -- the single clue that cracked the case
    outcome       TEXT,
    sentence      TEXT,
    investigation_tips TEXT,  -- lessons for future investigators
    tags          TEXT,   -- JSON list for semantic search
    source        TEXT
);

CREATE VIRTUAL TABLE IF NOT EXISTS solved_cases_fts
    USING fts5(title, crime_type, modus_operandi, key_evidence, how_solved,
               breakthrough, investigation_tips, tags, content=solved_cases, content_rowid=id);

CREATE TRIGGER IF NOT EXISTS fts_insert AFTER INSERT ON solved_cases BEGIN
    INSERT INTO solved_cases_fts(rowid, title, crime_type, modus_operandi, key_evidence,
        how_solved, breakthrough, investigation_tips, tags)
    VALUES (new.id, new.title, new.crime_type, new.modus_operandi, new.key_evidence,
        new.how_solved, new.breakthrough, new.investigation_tips, new.tags);
END;
"""

CASES = [
    # ── KARNATAKA CASES ───────────────────────────────────────────────────────
    {
        "title": "Kotwal Ramesh Murder (Bengaluru Gangland)",
        "year": 2000, "location": "Bengaluru", "state": "Karnataka",
        "crime_type": "Organized Crime / Murder",
        "victim": "Kotwal Ramesh, gang leader",
        "accused": "Rival gang members, contract killers",
        "modus_operandi": "Broad daylight shooting at a public petrol station by hired gunmen on motorcycles.",
        "key_evidence": json.dumps(["CCTV footage from petrol station", "Ballistic match on .32 revolver", "Witness statements from bystanders", "Mobile call records linking hired killers to gang boss"]),
        "how_solved": "CCTV footage identified the motorcycle number plate. Call detail records (CDRs) established contact between the shooters and the rival gang boss 2 hours before the murder.",
        "breakthrough": "Partial number plate on CCTV led to registered owner who turned witness.",
        "outcome": "Convicted. Multiple accused sentenced under IPC 302 and Karnataka Control of Organised Crime Act.",
        "sentence": "Life imprisonment for principal accused",
        "investigation_tips": json.dumps(["Always secure CCTV in 500m radius within 1 hour", "CDR analysis is critical in contract killings", "Motorcycle riders in gang hits often share a common supplier — check second-hand bike dealers"]),
        "tags": json.dumps(["gang", "shooting", "CCTV", "CDR", "contract killing", "bengaluru", "organized crime"]),
        "source": "Karnataka High Court records, public judgment"
    },
    {
        "title": "Bengaluru BPO Employee Pratibha Srikanth Murthy Murder",
        "year": 2005, "location": "Bengaluru", "state": "Karnataka",
        "crime_type": "Murder / Rape",
        "victim": "Pratibha Srikanth Murthy, 22, BPO employee",
        "accused": "Shivakumar, cab driver",
        "modus_operandi": "Victim dropped alone in cab late night, attacked, body dumped in lake. Driver continued regular routes.",
        "key_evidence": json.dumps(["Cab company records linking driver to last trip", "DNA match from victim's clothing", "Body found in lake near cab route", "Driver's inconsistent statements"]),
        "how_solved": "BPO cab logs showed Shivakumar was last driver. DNA from saliva on victim's dupatta matched accused. Victim's belongings found hidden at driver's home.",
        "breakthrough": "DNA evidence from victim's scarf — first major DNA-solved case in Karnataka.",
        "outcome": "Convicted under IPC 302, 376",
        "sentence": "Death sentence (later commuted to life)",
        "investigation_tips": json.dumps(["Night-shift employees: always verify cab logs within hours", "DNA from clothing fibers and saliva is critical — preserve evidence before washing", "Cab company GPS/route data is legally admissible"]),
        "tags": json.dumps(["BPO", "cab", "DNA", "rape murder", "bengaluru", "night shift", "working women"]),
        "source": "Karnataka High Court, SC appeal records"
    },
    {
        "title": "Aditi Murder Case (Bengaluru Real Estate Fraud)",
        "year": 2012, "location": "Bengaluru", "state": "Karnataka",
        "crime_type": "Murder / Fraud",
        "victim": "Aditi, real estate agent",
        "accused": "Business partner",
        "modus_operandi": "Victim killed after discovering accused was siphoning real estate funds. Body buried in site compound.",
        "key_evidence": json.dumps(["Last seen CCTV at accused's office", "Victim's missing phone found dismantled at accused's home", "Bank records showing fund siphoning", "Ground-penetrating radar located buried body"]),
        "how_solved": "Financial motive established from audit of joint accounts. Ground-penetrating radar used in construction site located body 4 feet underground.",
        "breakthrough": "Victim's phone SIM card found cut up in accused's dustbin.",
        "outcome": "Convicted IPC 302 + cheating charges",
        "sentence": "Life imprisonment",
        "investigation_tips": json.dumps(["In white-collar adjacent murders, follow the money first", "Ground penetrating radar — standard tool for suspected burial sites", "Phone components can survive even if device is destroyed — check dustbins"]),
        "tags": json.dumps(["real estate", "fraud", "buried body", "financial motive", "GPR", "bengaluru"]),
        "source": "Bengaluru City Civil Court records"
    },
    {
        "title": "Mysuru Kidnap for Ransom — IT Professional",
        "year": 2018, "location": "Mysuru", "state": "Karnataka",
        "crime_type": "Kidnapping for Ransom",
        "victim": "IT professional, 34",
        "accused": "Gang of 4, including former driver",
        "modus_operandi": "Victim followed from office, abducted near home, held in farmhouse. Ransom demand via encrypted messaging app.",
        "key_evidence": json.dumps(["Cell tower data placing accused near abduction site", "Ransom call traced via IMEI switching", "Farmhouse owner's land records linking to accused's relative", "Victim GPS watch data"]),
        "how_solved": "Victim's smartwatch continued syncing location silently. Family shared GPS data with police who triangulated the farmhouse location.",
        "breakthrough": "Victim's Apple Watch location shared by family — kidnappers didn't know about it.",
        "outcome": "All 4 convicted",
        "sentence": "10 years rigorous imprisonment each",
        "investigation_tips": json.dumps(["Always ask victim's family about wearables and IoT devices immediately", "Ransom calls switch SIMs but IMEI stays — track IMEI not SIM", "Former employees are top suspects in targeted kidnapping"]),
        "tags": json.dumps(["kidnapping", "ransom", "smartwatch", "GPS", "IMEI", "mysuru", "IT employee"]),
        "source": "Mysuru Sessions Court"
    },
    {
        "title": "Mangaluru Acid Attack Case",
        "year": 2014, "location": "Mangaluru", "state": "Karnataka",
        "crime_type": "Acid Attack",
        "victim": "Young woman, 19, student",
        "accused": "Rejected suitor, 22",
        "modus_operandi": "Perpetrator purchased acid from hardware shop, attacked victim near college gate, fled on bicycle.",
        "key_evidence": json.dumps(["Hardware shop CCTV showing acid purchase", "Shop keeper identification", "Bicycle tracked via nearby cameras", "Victim's phone showing threatening messages prior to attack"]),
        "how_solved": "Shop keeper identified buyer from photo lineup. Prior threatening WhatsApp messages from accused recovered from victim's phone cloud backup.",
        "breakthrough": "Cloud backup of victim's phone showed 47 threatening messages from accused in prior month.",
        "outcome": "Convicted under IPC 326A (acid attack provisions)",
        "sentence": "10 years imprisonment + fine",
        "investigation_tips": json.dumps(["Always check cloud backups of victim's phone — messages survive even if phone is destroyed", "Acid purchases are regulated — hardware shops must log buyer details (check compliance)", "Rejected suitors are primary suspects in targeted attacks on women"]),
        "tags": json.dumps(["acid attack", "harassment", "cloud backup", "WhatsApp", "mangaluru", "gender crime", "rejected suitor"]),
        "source": "Karnataka HC judgment 2016"
    },
    {
        "title": "Hubballi Railway Platform Murder",
        "year": 2017, "location": "Hubballi", "state": "Karnataka",
        "crime_type": "Murder",
        "victim": "Rashmitha, 21, student",
        "accused": "Naveen (stalker), 23",
        "modus_operandi": "Victim attacked with knife on crowded railway platform in broad daylight after rejecting accused's advances.",
        "key_evidence": json.dumps(["200+ witnesses on platform", "Railway CCTV — 6 camera angles", "Knife recovered from tracks", "Accused's Facebook messages showing obsession"]),
        "how_solved": "Accused identified within 30 minutes from CCTV. Arrested at his home village 80km away based on his previous address from social media profile.",
        "breakthrough": "Accused had posted his village photos on Facebook — located immediately.",
        "outcome": "Convicted IPC 302",
        "sentence": "Death sentence",
        "investigation_tips": json.dumps(["Railway platforms have multi-angle CCTV — request all feeds within 1 hour before recording loops", "Social media location data can locate fugitives faster than traditional methods", "Stalking cases: always check social media history of both victim and accused before questioning"]),
        "tags": json.dumps(["stalking", "knife", "railway", "CCTV", "social media", "hubballi", "femicide"]),
        "source": "HC Karnataka 2019, widely reported"
    },
    {
        "title": "Bengaluru Ponzi Scheme — IMA Jewels",
        "year": 2019, "location": "Bengaluru", "state": "Karnataka",
        "crime_type": "Financial Fraud / Ponzi Scheme",
        "victim": "40,000+ investors, minority community",
        "accused": "Mohammed Mansoor Khan, IMA founder",
        "modus_operandi": "Promised 3-4% monthly returns on Islamic finance investments. Used new investor money to pay old investors. Collapsed when redemptions exceeded deposits.",
        "key_evidence": json.dumps(["Forged property documents used as collateral", "Hawala trail traced through ED", "Accused fled to Dubai — Interpol Red Notice issued", "Victim ledgers showing promised vs actual payments"]),
        "how_solved": "ED froze assets and traced hawala network. Accused was deported from Dubai after Red Notice. Digital transactions revealed actual fund flow vs claimed investments.",
        "breakthrough": "Accused sent a WhatsApp audio claiming political protection — audio made public and triggered investor riots, forcing police action.",
        "outcome": "Arrested, chargesheeted. ED attached Rs 900 crore in assets.",
        "sentence": "Trial ongoing (2024)",
        "investigation_tips": json.dumps(["Ponzi schemes: always audit the ratio of redemptions to new deposits — Ponzi collapses when ratio exceeds 1", "Religious/community-targeted frauds often have political protection — document political connections early", "Hawala networks leave digital traces via mobile money transfers"]),
        "tags": json.dumps(["ponzi", "fraud", "hawala", "IMA", "bengaluru", "financial crime", "minority community", "WhatsApp evidence"]),
        "source": "ED chargesheet, public records, HC bail hearings"
    },
    {
        "title": "Bengaluru Serial Burglar — Operation Safe Home",
        "year": 2020, "location": "Bengaluru", "state": "Karnataka",
        "crime_type": "Serial Burglary",
        "victim": "67 households across 8 localities",
        "accused": "Gang of 3, led by Raju alias Cycle Raju",
        "modus_operandi": "Targeted apartments when families on vacation. Identified targets from Instagram posts showing travel plans. Entered via bathroom ventilators.",
        "key_evidence": json.dumps(["Instagram accounts of victims followed by burner accounts", "Same ventilator forced-entry method across all 67 cases", "Stolen gold sold to same three jewellers", "Fingerprint match in case #34"]),
        "how_solved": "Link analysis of stolen jewellery traced buyers to same fence. Single fingerprint from case #34 matched accused's existing record.",
        "breakthrough": "Victims had tagged their holiday locations on Instagram — burglars monitored the feed.",
        "outcome": "Convicted in 67 cases",
        "sentence": "7 years per case (concurrent)",
        "investigation_tips": json.dumps(["Serial burglary: always look for MO similarity across cases — same entry method = same perpetrator", "Check if victims had posted travel plans on social media before the burglary", "Stolen gold travels through fences — track jewellery buyers in the area"]),
        "tags": json.dumps(["burglary", "serial", "instagram", "social media", "fingerprint", "bengaluru", "modus operandi"]),
        "source": "Bengaluru Police press release, trial court records"
    },

    # ── KARNATAKA CYBER CASES ─────────────────────────────────────────────────
    {
        "title": "Bengaluru ATM Card Cloning Network",
        "year": 2021, "location": "Bengaluru", "state": "Karnataka",
        "crime_type": "Cyber Crime / ATM Fraud",
        "victim": "1,200+ bank customers, Rs 3.2 crore total",
        "accused": "Romanian-origin gang + local recruiters",
        "modus_operandi": "Skimming devices installed on ATMs in upscale areas. Cloned cards used in Europe and USA within hours of cloning.",
        "key_evidence": json.dumps(["Skimming device recovered from ATM with fingerprints", "ATM CCTV showed device installation", "International card-present transactions within 6 hours of skimming", "Interpol alert on cloned card usage in Romania"]),
        "how_solved": "Bank flagged unusual overseas usage pattern. ATM CCTV recovered before tape loop. Foreign nationals identified via immigration records.",
        "breakthrough": "Skimming device had manufacturer's serial number — traced to Bulgarian black-market supplier known to Interpol.",
        "outcome": "6 convicted including 2 foreign nationals deported after sentence",
        "sentence": "3-5 years + deportation",
        "investigation_tips": json.dumps(["ATM fraud: check overseas card usage within 6 hours of reported skimming", "Skimming devices have unique RF signatures — use RF scanner at ATM", "Always recover ATM CCTV within 24 hours — most ATMs loop every 72 hours"]),
        "tags": json.dumps(["ATM", "skimming", "cyber", "banking fraud", "international", "bengaluru", "card cloning"]),
        "source": "CBI chargesheet, RBI advisory"
    },
    {
        "title": "Dharwad Cyber Sextortion Ring",
        "year": 2022, "location": "Dharwad", "state": "Karnataka",
        "crime_type": "Cyber Crime / Sextortion",
        "victim": "350+ victims across India, mostly professionals",
        "accused": "Gang of 8 operating from Dharwad and Rajasthan (Mewat)",
        "modus_operandi": "Fake social media profiles of women, video calls to victims, recorded compromising content, threatened to send to employer/family.",
        "key_evidence": json.dumps(["VoIP numbers traced to physical addresses via RJio data", "Same 4 bank accounts received all extortion payments", "Victim screen recordings submitted as evidence", "Geolocation of IP addresses"]),
        "how_solved": "Multiple victims filed complaints. CEN (Cyber Economic Narcotics) unit linked cases via same receiving bank accounts. Dharwad-Mewat connection established through IP geolocation.",
        "breakthrough": "All extortion payments went to 4 accounts — banking trail led directly to gang.",
        "outcome": "8 arrested, 350 complainants consolidated",
        "sentence": "Trial ongoing",
        "investigation_tips": json.dumps(["Sextortion: never negotiate — payment encourages repeat demands", "Multiple small payments to same account = clear pattern — flag with bank", "VoIP numbers can be geolocated via telecom provider cooperation"]),
        "tags": json.dumps(["sextortion", "cyber", "VoIP", "mewat gang", "dharwad", "social media fraud", "bank account trail"]),
        "source": "Karnataka CEN police, IT cell press releases"
    },

    # ── FAMOUS NATIONAL CASES ─────────────────────────────────────────────────
    {
        "title": "Aarushi-Hemraj Double Murder",
        "year": 2008, "location": "Noida", "state": "Uttar Pradesh",
        "crime_type": "Double Murder",
        "victim": "Aarushi Talwar (14, daughter) and Hemraj (domestic help)",
        "accused": "Rajesh Talwar (father), acquitted on appeal",
        "modus_operandi": "Both victims killed with sharp object overnight in locked apartment. Hemraj's body found on terrace next day.",
        "key_evidence": json.dumps(["Golf club (likely murder weapon) cleaned but blood traces found", "Alcohol smell at scene", "Last call records from Hemraj's phone", "Parents as only adults in house", "CBI vs UP Police conflicting findings"]),
        "how_solved": "Case was controversial — two separate agencies reached opposite conclusions. Allahabad HC acquitted parents citing 'benefit of doubt' due to investigative failures.",
        "breakthrough": "ABSENCE of evidence: terrace door was locked from inside, only Rajesh had key — but HC said this was circumstantial.",
        "outcome": "Acquitted by Allahabad HC 2017",
        "sentence": "N/A (acquitted)",
        "investigation_tips": json.dumps(["Multiple agencies investigating same case leads to evidence contamination", "Scene must be sealed immediately — Aarushi's room was accessed by 20+ people before forensics arrived", "Locked-room mysteries require meticulous documentation of ALL keys and access points", "Never announce suspects publicly before arrest — taints witness testimony"]),
        "tags": json.dumps(["double murder", "locked room", "investigation failure", "contaminated evidence", "noida", "controversial", "CBI"]),
        "source": "Allahabad HC judgment 2017, public record"
    },
    {
        "title": "Sheena Bora Murder",
        "year": 2012, "location": "Mumbai", "state": "Maharashtra",
        "crime_type": "Murder / Family Crime",
        "victim": "Sheena Bora, 24 (daughter of accused)",
        "accused": "Indrani Mukerjea (mother), Peter Mukerjea, Sanjeev Khanna",
        "modus_operandi": "Victim strangled in car, body burned in Raigad forest. Victim's existence denied publicly. Case surfaced 3 years later when driver arrested for separate crime.",
        "key_evidence": json.dumps(["Driver Shyamvar Rai's confession after arrest for illegal arms", "Burned remains identified via DNA after 3 years", "Call records showing victim's last location", "Bank account manipulation after death"]),
        "how_solved": "Driver arrested for separate arms case confessed to involvement. DNA matched burned skeletal remains to victim's family members.",
        "breakthrough": "Accused's driver was arrested on an unrelated arms charge and confessed — unrelated arrests often unlock major crimes.",
        "outcome": "Indrani Mukerjea convicted 2024",
        "sentence": "Life imprisonment",
        "investigation_tips": json.dumps(["Always verify 'missing person' reports against burned/unidentified remains in the region", "Unrelated arrests can unlock major crimes — always conduct background check on all arrestees", "Family financial records after a disappearance can confirm foul play"]),
        "tags": json.dumps(["family murder", "burn body", "DNA", "confession", "unrelated arrest", "mumbai", "media family"]),
        "source": "Bombay HC, Supreme Court, public judgments"
    },
    {
        "title": "Nirbhaya Gang Rape and Murder",
        "year": 2012, "location": "Delhi", "state": "Delhi",
        "crime_type": "Gang Rape / Murder",
        "victim": "Jyoti Singh (23), paramedic student",
        "accused": "Ram Singh, Mukesh Singh, Vinay Sharma, Akshay Thakur, Pawan Gupta + 1 juvenile",
        "modus_operandi": "Victim lured into private bus, gang-raped for 2+ hours, thrown from moving bus with male companion. Died 13 days later in Singapore hospital.",
        "key_evidence": json.dumps(["Bus identified via partial number plate + witness", "DNA from all 6 accused on victim", "Conductor's testimony", "CCTV at various bus stops", "Iron rod recovered from Yamuna river"]),
        "how_solved": "Bus identified within 48 hours from witness description. All 6 arrested within 5 days. DNA confirmed involvement of all accused.",
        "breakthrough": "Bus driver's error — turned wrong at a traffic check. The traffic constable noted the bus number.",
        "outcome": "5 convicted (Ram Singh died in custody), juvenile served 3 years",
        "sentence": "Death by hanging (executed March 2020 after 7 years of appeals)",
        "investigation_tips": json.dumps(["Rape-murder in vehicles: secure bus/taxi DNA evidence before vehicle is moved", "Traffic constable logs can identify vehicles at specific times — check all duty registers", "Companion/survivor is the most critical witness — record statement immediately"]),
        "tags": json.dumps(["gang rape", "murder", "bus", "DNA", "death penalty", "delhi", "landmark case", "fast track court"]),
        "source": "Delhi HC, Supreme Court — public landmark judgment"
    },
    {
        "title": "Jessica Lal Murder",
        "year": 1999, "location": "Delhi", "state": "Delhi",
        "crime_type": "Murder",
        "victim": "Jessica Lal, model and bartender",
        "accused": "Manu Sharma, son of Congress politician",
        "modus_operandi": "Victim shot at party after refusing to serve alcohol after closing. 300+ witnesses. Accused acquitted initially due to witness tampering.",
        "key_evidence": json.dumps([".22 pistol recovered", "Ballistic match", "300 witnesses initially (most turned hostile)", "SMS campaign by public pressured retrial", "Key witness Shyan Munshi recanted then re-testified"]),
        "how_solved": "Initial acquittal due to mass witness turning hostile under political pressure. Media campaign and public SMS drive forced Delhi HC to reopen. Key witness re-testified. Accused convicted on retrial.",
        "breakthrough": "Media campaign with 200,000 SMSes sent to Delhi Police Commissioner forced review — public pressure secured justice.",
        "outcome": "Convicted on retrial",
        "sentence": "Life imprisonment",
        "investigation_tips": json.dumps(["Witness protection is critical in high-profile cases involving powerful accused", "Ballistic evidence is objective — preserve it regardless of witness hostility", "Document all 'hostile' witness turnarounds — intimidation is itself an offense"]),
        "tags": json.dumps(["murder", "witness tampering", "political influence", "retrial", "media pressure", "delhi", "landmark"]),
        "source": "Delhi HC retrial judgment 2006, public record"
    },
    {
        "title": "Nithari Serial Murders",
        "year": "2005-2006", "location": "Noida", "state": "Uttar Pradesh",
        "crime_type": "Serial Murder / Cannibalism",
        "victim": "16+ children and women",
        "accused": "Moninder Singh Pandher (employer) + Surinder Koli (domestic help)",
        "modus_operandi": "Children lured to bungalow. Koli killed, engaged in necrophilia and cannibalism. Remains discarded in drain behind house. Missing persons ignored by local police for 2 years.",
        "key_evidence": json.dumps(["Skeletal remains in drain behind D-5, Nithari", "DNA matched 16 missing children", "Koli's detailed confessional statement", "Bones with cut marks indicating cannibalism"]),
        "how_solved": "Local residents complained of smell. UP Police initially ignored. Skeletal remains found in drain in 2006. DNA matched children reported missing since 2004.",
        "breakthrough": "A local resident's persistent complaint about the drain smell — police had ignored it for 2 years.",
        "outcome": "Koli convicted and executed 2023. Pandher acquitted in some cases.",
        "sentence": "Koli: death penalty, executed; Pandher: acquitted in murder, convicted in other offences",
        "investigation_tips": json.dumps(["Serial missing children in one area = serial perpetrator. Cluster analysis is essential.", "Neighbours' smell/noise complaints near a property with missing persons reports — always investigate", "Police inaction in early missing person cases enabled 16 murders — mandatory FIR is critical"]),
        "tags": json.dumps(["serial murder", "children", "cannibalism", "DNA", "missing persons", "police inaction", "noida", "landmark"]),
        "source": "CBI chargesheet, Allahabad HC, SC judgment"
    },
    {
        "title": "Rajiv Gandhi Assassination",
        "year": 1991, "location": "Sriperumbudur", "state": "Tamil Nadu",
        "crime_type": "Political Assassination / Suicide Bombing",
        "victim": "Rajiv Gandhi, former Prime Minister",
        "accused": "LTTE network, Dhanu (suicide bomber), Sivarasan (handler)",
        "modus_operandi": "Suicide belt bomb detonated by Dhanu in a crowd during election rally. 18 others killed. Handler Sivarasan evaded capture for months.",
        "key_evidence": json.dumps(["Photographer Haribabu's undeveloped camera film survived blast — captured bomber's face", "Sivarasan's sketch from surviving LTTE informants", "Belt bomb components traced to LTTE workshops", "Safe house network mapped through informants"]),
        "how_solved": "Camera of dead photographer was developed — showed face of bomber moments before detonation. Sivarasan and gang found 2 months later — died by suicide when cornered.",
        "breakthrough": "A dead photographer's camera contained the bomber's face — developed by forensic lab.",
        "outcome": "26 convicted. 7 originally on death row, commuted to life by SC 2014. Nalini Sriharan released 2022.",
        "sentence": "Multiple life imprisonments",
        "investigation_tips": json.dumps(["Bombing scenes: recover ALL cameras/devices near the scene — images may capture pre-blast", "Suicide bombing: bomber's fragments contain DNA — identify bomber from remains", "Handlers stay close — search 2km radius for surveillance post after blast"]),
        "tags": json.dumps(["assassination", "bomb", "LTTE", "political", "suicide bomber", "camera evidence", "forensic photography", "tamil nadu"]),
        "source": "SC judgment 1999, public record"
    },
    {
        "title": "Naina Sahni Tandoor Murder",
        "year": 1995, "location": "Delhi", "state": "Delhi",
        "crime_type": "Murder / Body Disposal",
        "victim": "Naina Sahni, 29, Congress youth wing leader",
        "accused": "Sushil Sharma (husband), Congress politician",
        "modus_operandi": "Victim shot by husband at home, body taken to Bagiya restaurant, stuffed into tandoor oven to destroy evidence. Restaurant staff raised alarm.",
        "key_evidence": json.dumps(["Restaurant staff called police on smell", "Partially burned body recovered from tandoor", "Ballistic match on Sharma's licensed pistol", "Bone fragments with bullet fragments", "Staff eyewitness testimony"]),
        "how_solved": "Restaurant staff became suspicious of smoke and smell at 2am. Called police. Sharma initially tried to bribe constable. Body recovered mid-burning.",
        "breakthrough": "Restaurant staff's bravery in calling police despite accused threatening them.",
        "outcome": "Convicted",
        "sentence": "Death sentence commuted to life 2013",
        "investigation_tips": json.dumps(["Unusual burning smells at odd hours near commercial premises — always investigate", "Partial body destruction still leaves identifiable evidence: teeth, bone, DNA", "Initial bribe attempt is itself evidence of consciousness of guilt — document it"]),
        "tags": json.dumps(["murder", "body disposal", "burning", "tandoor", "delhi", "political", "restaurant", "landmark"]),
        "source": "Delhi HC judgment, public record"
    },
    {
        "title": "Priyadarshini Mattoo Rape and Murder",
        "year": 1996, "location": "Delhi", "state": "Delhi",
        "crime_type": "Rape and Murder",
        "victim": "Priyadarshini Mattoo, 25, law student",
        "accused": "Santosh Kumar Singh, IPS officer's son",
        "modus_operandi": "Victim raped and strangled in her flat after she rejected accused. Accused was known to stalk her. Initial acquittal due to political influence.",
        "key_evidence": json.dumps(["DNA evidence matching accused", "Fingerprints at scene", "History of stalking documented by victim to police", "Victim's diary detailing harassment"]),
        "how_solved": "DNA matched accused conclusively. Trial court acquitted despite evidence. Delhi HC reversed, SC confirmed conviction 2010 — 14 years after crime.",
        "breakthrough": "Victim had documented the stalking in writing — her diary became key evidence.",
        "outcome": "Convicted",
        "sentence": "Death (commuted to life)",
        "investigation_tips": json.dumps(["Victim's written records of prior harassment are extremely strong evidence — always secure diaries, notebooks, emails", "IPS/political family accused: preserve all evidence under double lock, submit copies to CBI immediately", "Stalking must be treated as precursor to violence — FIR mandatory"]),
        "tags": json.dumps(["rape murder", "stalking", "IPS", "political influence", "DNA", "diary evidence", "delayed justice", "delhi"]),
        "source": "SC judgment 2010, public record"
    },
    {
        "title": "BMW Hit and Run — Sanjeev Nanda Case",
        "year": 1999, "location": "Delhi", "state": "Delhi",
        "crime_type": "Culpable Homicide / Hit and Run",
        "victim": "6 persons including police constables",
        "accused": "Sanjeev Nanda, grandson of Navy Chief",
        "modus_operandi": "Drunk driving at 4am. BMW ran over sleeping pavement dwellers and policemen. Fled scene. Car cleaned. Witness intimidation followed.",
        "key_evidence": json.dumps(["Blood on BMW undercarriage despite cleaning", "Witness Sunil Kulkarni (turned hostile, later reconsidered)", "Night guard at nearby hotel saw car with damaged bumper", "Forensic analysis of BMW body parts"]),
        "how_solved": "Blood traces recovered despite cleaning attempt. Key witness recanted, but forensic evidence was conclusive. Trial took 8 years due to delays.",
        "breakthrough": "Hotel night guard documented partial number plate — connected to Nanda's BMW.",
        "outcome": "Convicted under IPC 304A",
        "sentence": "5 years imprisonment (reduced on appeal)",
        "investigation_tips": json.dumps(["Vehicle crime scenes: even cleaned vehicles retain blood in door seals, undercarriage, brake lines", "Always record statements from ALL witnesses at scene within 2 hours before intimidation begins", "Powerful family accused: hand vehicle immediately to forensic team, not local police"]),
        "tags": json.dumps(["hit and run", "drunk driving", "BMW", "elite accused", "witness intimidation", "forensics", "delhi", "navy family"]),
        "source": "Delhi HC, SC judgment 2012, public record"
    },
    {
        "title": "Hyderabad Disha Rape and Murder",
        "year": 2019, "location": "Hyderabad", "state": "Telangana",
        "crime_type": "Gang Rape / Murder",
        "victim": "Priyanka Reddy (Disha), 26, veterinarian",
        "accused": "Mohammed Areef, Jollu Shiva, Jollu Naveen, Chintakunta Chennakeshavulu",
        "modus_operandi": "Victim's scooter tyre punctured deliberately. Offered help, gang-raped, strangled, body burned under flyover.",
        "key_evidence": json.dumps(["Toll plaza CCTV showing vehicle", "Victim's phone location data", "Burn site forensics — shoe print match", "Accused phone location data at crime scene time", "DNA match"]),
        "how_solved": "Victim's last call to sister ('some strangers are helping me') traced to tower. Accused phones located near crime scene via CDR. Arrested within 48 hours.",
        "breakthrough": "Victim called sister during the setup — tower location + time narrowed suspects to people in that area with prior records.",
        "outcome": "Accused killed in alleged police encounter 2019",
        "sentence": "N/A (encounter deaths, controversial)",
        "investigation_tips": json.dumps(["Victim's last call is critical — tower data locates them AND potential witnesses", "Deliberate tyre puncture as lure: check for puncture tool, test if puncture is recent/sharp", "Burn sites retain evidence for days — DNA from bone, shoe prints in ash"]),
        "tags": json.dumps(["gang rape", "murder", "encounter", "hyderabad", "CDR", "DNA", "tyre puncture lure", "veterinarian"]),
        "source": "Telangana HC, public record, SIT report"
    },
    {
        "title": "Sunanda Pushkar Death",
        "year": 2014, "location": "Delhi", "state": "Delhi",
        "crime_type": "Suspicious Death / Possible Homicide",
        "victim": "Sunanda Pushkar, 52, wife of minister Shashi Tharoor",
        "accused": "Shashi Tharoor (charges filed, later dropped)",
        "modus_operandi": "Found dead in hotel suite. Initial finding: overdose. Later changed to unnatural death. Alprazolam poisoning suspected.",
        "key_evidence": json.dumps(["Injection mark on body identified by AIIMS", "Poison detected in viscera report", "Hotel CCTV showing visitors", "WhatsApp argument logs night before death"]),
        "how_solved": "Not fully resolved. Tharoor was chargesheeted for abetment of suicide, charges later dropped by court citing insufficient evidence.",
        "breakthrough": "AIIMS revised its initial opinion — injection mark indicated external alprazolam administration, not self-ingestion.",
        "outcome": "No conviction — case closed 2023",
        "sentence": "N/A",
        "investigation_tips": json.dumps(["Hotel deaths of high-profile persons: seal room, secure all CCTV before VIP entourage removes evidence", "Second opinion from AIIMS is standard in celebrity/political deaths", "Digital communications (WhatsApp) must be preserved before next-of-kin wipes phone"]),
        "tags": json.dumps(["suspicious death", "poisoning", "hotel", "political", "delhi", "AIIMS", "WhatsApp", "unresolved"]),
        "source": "Delhi HC orders, public record"
    },
    {
        "title": "Arushi Talwar Case — CBI vs UP Police Conflict",
        "year": 2008, "location": "Noida", "state": "Uttar Pradesh",
        "crime_type": "Investigative Failure Case Study",
        "victim": "Aarushi Talwar and Hemraj",
        "accused": "Multiple theories: parents, domestic staff",
        "modus_operandi": "Double murder in closed apartment. Terrace door locked. Scene compromised before forensics. Two agencies with conflicting theories.",
        "key_evidence": json.dumps(["Golf club (cleaned, partial DNA)", "Scotch bottle at scene", "Terrace door key control", "Hemraj's phone CDR"]),
        "how_solved": "Not solved — Talwars acquitted by HC. Investigative failure case study.",
        "breakthrough": "No breakthrough — this case is a lesson in what NOT to do.",
        "outcome": "Acquittal due to reasonable doubt created by investigation failures",
        "sentence": "N/A",
        "investigation_tips": json.dumps(["Crime scene must be sealed IMMEDIATELY — no entry without PPE and evidence log", "Single agency must own the investigation — multiple agencies create conflicting theories that help defense", "Document every person who enters scene with timestamp", "Announce suspects AFTER arrest, not before"]),
        "tags": json.dumps(["investigation failure", "contaminated scene", "multiple agencies", "noida", "lesson", "double murder", "acquittal"]),
        "source": "Allahabad HC acquittal judgment 2017"
    },
    {
        "title": "2008 Mumbai Terror Attacks (26/11)",
        "year": 2008, "location": "Mumbai", "state": "Maharashtra",
        "crime_type": "Terrorism / Mass Murder",
        "victim": "166 killed, 300+ injured",
        "accused": "Lashkar-e-Taiba (Pakistan), Ajmal Kasab + 9 killed during attack",
        "modus_operandi": "10 gunmen arrived by sea from Pakistan. Split into teams to attack 4 sites: CST, Taj hotel, Oberoi hotel, Nariman House. Kasab alone captured alive.",
        "key_evidence": json.dumps(["Kasab captured alive with weapon and GPS", "Rubber dinghy traced to fishing vessel Al-Husseini (Pakistani)", "Satellite phone intercepts", "GPS devices showing route from Pakistan", "Hotel CCTV footage of all attackers"]),
        "how_solved": "Kasab's capture provided direct confessional evidence. GPS logs on captured device showed complete route from Pakistani waters. Satellite phone intercepts proved LeT direction from Pakistan.",
        "breakthrough": "Kasab survived after being shot — provided real-time intelligence on Pakistani handlers during 60-hour standoff.",
        "outcome": "Kasab convicted and hanged 2012. Pakistan refused full cooperation.",
        "sentence": "Kasab: death by hanging November 2012",
        "investigation_tips": json.dumps(["Terror attack: prioritize capturing one attacker alive for intelligence — more valuable than neutralization", "GPS devices on terrorists contain entire route history — preserve immediately", "Satellite phone intercepts require prior court authorization — maintain standing orders for terror scenarios", "Hotel CCTV from multiple angles reconstructs entire attack timeline"]),
        "tags": json.dumps(["terrorism", "26/11", "mumbai", "GPS", "captured alive", "Pakistan", "satellite phone", "mass murder"]),
        "source": "SC judgment 2012, NIA report, public record"
    },
    {
        "title": "Vyapam Scam — Serial Suspicious Deaths",
        "year": "2009-2013", "location": "Bhopal", "state": "Madhya Pradesh",
        "crime_type": "Corruption / Suspicious Deaths",
        "victim": "50+ persons linked to case died under suspicious circumstances",
        "accused": "Senior politicians, officials, exam contractors",
        "modus_operandi": "Exam scam (fake candidates, impersonation) in government recruitment exams. Witnesses, accused, and journalists connected to case died at high rate.",
        "key_evidence": json.dumps(["SIM cards used by impersonators", "Forged admit cards", "Bank transfers to middlemen", "List of 55 persons who died connected to case"]),
        "how_solved": "Partially — SC transferred to CBI. Many accused died before trial. Scam exposed by journalist Naveen Gupta.",
        "breakthrough": "A teacher refused to let an impersonator sit the exam and reported it — one complaint triggered the largest exam scam investigation in India.",
        "outcome": "2500+ arrested. Main political accused died before conviction.",
        "sentence": "Various prison terms for middlemen and impersonators",
        "investigation_tips": json.dumps(["When witnesses in a case start dying at anomalous rates — escalate immediately to SC/SIT", "Exam fraud: biometric verification at exam centers is the only reliable deterrent", "Transfer high-risk cases to neutral agency when local political interference is evident"]),
        "tags": json.dumps(["corruption", "exam fraud", "suspicious deaths", "madhya pradesh", "political", "CBI transfer", "whistleblower"]),
        "source": "SC orders, CBI chargesheet excerpts, public record"
    },
    {
        "title": "Lalit Mohan Thapar Murder (Chandigarh NRI Property Fraud)",
        "year": 2015, "location": "Chandigarh", "state": "Punjab",
        "crime_type": "Murder / Property Fraud",
        "victim": "Lalit Mohan Thapar, 68, NRI businessman",
        "accused": "Property agent and accomplice",
        "modus_operandi": "Victim came from UK to dispute property transaction. Killed and body buried in under-construction building owned by accused.",
        "key_evidence": json.dumps(["Victim's UK mobile last pinged in Chandigarh", "Property transaction documents showing dispute", "Ground floor concrete showed recent pouring", "DNA from skeletal remains matched victim's UK family"]),
        "how_solved": "UK family filed missing person. NRI Wing traced last tower location. Property dispute history established motive. Construction site excavated on tip from sub-contractor.",
        "breakthrough": "Sub-contractor told police about 'urgent concrete work' on a Sunday night — inconsistent with normal construction schedule.",
        "outcome": "Convicted",
        "sentence": "Life imprisonment",
        "investigation_tips": json.dumps(["NRI murder: always coordinate with UK/USA consulate for victim's digital footprint", "Sudden 'off-schedule' construction activity near where a person was last seen — investigate immediately", "DNA comparison with overseas family requires INTERPOL coordination — initiate early"]),
        "tags": json.dumps(["NRI", "property fraud", "murder", "buried body", "concrete", "Punjab", "UK Indian"]),
        "source": "Punjab and Haryana HC, public record"
    },
    {
        "title": "Gudiya Rape and Murder — Bulandshahr",
        "year": 2016, "location": "Bulandshahr", "state": "Uttar Pradesh",
        "crime_type": "Gang Rape and Murder",
        "victim": "Gudiya, 8 years old",
        "accused": "Neighbour Sarvesh + accomplice",
        "modus_operandi": "Child lured to isolated room, gang-raped, murdered, body thrown in sugarcane field.",
        "key_evidence": json.dumps(["DNA from victim body matched Sarvesh", "Child's bangles found at accused's house", "Witnesses saw victim near accused's house last", "POCSO provisions applied"]),
        "how_solved": "Mother's immediate complaint. DNA swab from accused matched. Bangles recovered during house search.",
        "breakthrough": "Mother insisted on DNA testing despite pressure to settle — DNA was conclusive.",
        "outcome": "Convicted under POCSO and IPC 302",
        "sentence": "Death sentence",
        "investigation_tips": json.dumps(["Child sexual murder: DNA swabs from all male neighbours within 200m — time-critical", "Child's personal items (bangles, clips, school bag) are frequently kept as trophies — search suspect's home immediately", "POCSO: special court, in-camera proceedings, child-friendly recording of evidence"]),
        "tags": json.dumps(["child murder", "rape", "POCSO", "DNA", "trophy evidence", "UP", "death penalty"]),
        "source": "Allahabad HC judgment, public record"
    },
    {
        "title": "Kolkata Doctor Rape and Murder — RG Kar Hospital",
        "year": 2024, "location": "Kolkata", "state": "West Bengal",
        "crime_type": "Rape and Murder",
        "victim": "Trainee doctor, 31",
        "accused": "Sanjoy Roy, civic volunteer",
        "modus_operandi": "Victim raped and murdered in seminar room of RG Kar Medical College during night duty. Body found in morning.",
        "key_evidence": json.dumps(["CCTV showing accused entering with bloody clothes", "DNA match from semen samples", "Accused's Bluetooth device pinged in seminar room", "Footwear match to crime scene"]),
        "how_solved": "Hospital CCTV showed accused entering seminar hall at 3am with blood on clothes. DNA conclusively matched. Bluetooth device location data placed accused at scene.",
        "breakthrough": "Bluetooth data from accused's earphones placed him in the seminar room at time of murder.",
        "outcome": "Convicted January 2025",
        "sentence": "Life imprisonment (no death penalty — landmark debate)",
        "investigation_tips": json.dumps(["Hospital crimes: Bluetooth device pings from victim and accused devices create precise location timeline", "Night-shift murder: ALL CCTV within the building must be seized within 2 hours of discovery", "DNA from semen is the gold standard — collect swabs before any medical procedure on the body"]),
        "tags": json.dumps(["doctor murder", "rape", "hospital", "Bluetooth evidence", "CCTV", "Kolkata", "2024", "DNA"]),
        "source": "Kolkata Sessions Court judgment 2025, public record"
    },
    {
        "title": "Patna Serial Killer — Chandrakant Jha",
        "year": "2004-2007", "location": "Delhi/Bihar", "state": "Delhi",
        "crime_type": "Serial Murder",
        "victim": "3 confirmed + suspected more, all body parts disposed near Tihar",
        "accused": "Chandrakant Jha",
        "modus_operandi": "Killed migrant workers from Bihar. Dismembered bodies. Left body parts outside Tihar Jail gate with taunting notes to police.",
        "key_evidence": json.dumps(["DNA from body parts", "Note paper with partial fingerprint", "Handwriting on notes", "Victim identification via DNA matching to Bihar families"]),
        "how_solved": "Accused taunted police by leaving notes outside Tihar jail. Handwriting analysis and fingerprint on one note led to arrest in 2007.",
        "breakthrough": "Taunting notes to police — the need to show superiority over police led to capture.",
        "outcome": "Convicted",
        "sentence": "Death penalty (commuted to life by HC)",
        "investigation_tips": json.dumps(["Serial killers often escalate taunting behaviour — take communications to police seriously", "Dismemberment: DNA from bone marrow survives decomposition — test all remains", "Migrant worker victims: coordinate with home state police for family DNA samples"]),
        "tags": json.dumps(["serial killer", "dismemberment", "DNA", "taunting", "notes", "delhi", "migrant worker"]),
        "source": "Delhi HC judgment, public record"
    },
    {
        "title": "Love Jihad Murder — Shraddha Walker",
        "year": 2022, "location": "Delhi", "state": "Delhi",
        "crime_type": "Murder / Body Disposal",
        "victim": "Shraddha Walker, 27",
        "accused": "Aftab Poonawala (live-in partner)",
        "modus_operandi": "Victim strangled during argument. Body dismembered into 35 parts. Parts stored in refrigerator for 2 weeks, then disposed in Mehrauli forest over 18 days.",
        "key_evidence": json.dumps(["Skull fragment with dental match", "Refrigerator with traces", "Phone data showing continued use of victim's apps by accused", "35 body part recovery sites mapped"]),
        "how_solved": "Father filed missing person. Accused initially claimed she left him. Police tracked phone — accused was using her UPI and ordering food for one. Forest disposal areas identified via cadaver dogs.",
        "breakthrough": "Accused kept using victim's Swiggy and Zomato apps ordering food for one — behavioural inconsistency flagged.",
        "outcome": "Trial ongoing (2024)",
        "sentence": "Under trial",
        "investigation_tips": json.dumps(["Digital behavioural analysis: check if missing person's apps (food delivery, UPI) are being used normally — indicates victim is held or dead", "Refrigerators retain DNA even after thorough cleaning — test all appliances", "Cadaver dogs trained for human remains in forests — deploy when body disposal suspected"]),
        "tags": json.dumps(["dismemberment", "refrigerator", "app behaviour", "cadaver dog", "delhi", "domestic violence", "body disposal"]),
        "source": "Delhi HC bail orders, chargesheet, public record"
    },
    {
        "title": "Sarabjit Singh Poisoning — Pakistan Prison",
        "year": 2013, "location": "Lahore", "state": "International",
        "crime_type": "Murder in Custody",
        "victim": "Sarabjit Singh, Indian national on death row in Pakistan",
        "accused": "Fellow prisoners (Mudassar and Amanat)",
        "modus_operandi": "Attacked with bricks and sharp objects in Lahore's Kot Lakhpat Jail. Died 6 days later.",
        "key_evidence": json.dumps(["Prison CCTV (disputed by Pakistan)", "Medical records from Lahore hospital", "Government of India diplomatic protest", "Victim's sister testimony on India TV"]),
        "how_solved": "India sought extradition and information — Pakistan refused to share full evidence. Diplomatic case only.",
        "breakthrough": "N/A — perpetrators were never prosecuted in Pakistan.",
        "outcome": "No prosecution. Diplomatic incident.",
        "sentence": "N/A",
        "investigation_tips": json.dumps(["International custody deaths: document all physical evidence through consular visit immediately", "Prison surveillance footage must be secured as highest priority in custody deaths", "Custody death investigation: independent medical examination before body release is critical"]),
        "tags": json.dumps(["custody death", "international", "Pakistan", "prison murder", "diplomatic", "Indian national"]),
        "source": "MEA statements, public record"
    },
    {
        "title": "Ansal Plaza Stalking and Murder — Sonia Murder Case",
        "year": 2003, "location": "Delhi", "state": "Delhi",
        "crime_type": "Stalking / Murder",
        "victim": "Sonia, 20, student",
        "accused": "Mintu alias Mohit Dahiya",
        "modus_operandi": "Victim repeatedly rejected accused. Accused confronted victim at Ansal Plaza mall, stabbed 9 times in public.",
        "key_evidence": json.dumps(["100+ eyewitnesses", "Mall CCTV", "Accused arrested at scene", "Prior complaint by victim of harassment"]),
        "how_solved": "Accused caught red-handed. Prior harassment complaint by victim established premeditation.",
        "breakthrough": "Victim had filed a complaint about stalking 3 weeks prior — police had taken no action.",
        "outcome": "Convicted IPC 302",
        "sentence": "Life imprisonment",
        "investigation_tips": json.dumps(["Stalking complaint = threat to life — issue formal warning letter to stalker and record in station diary", "Prior victim complaint establishes premeditation, elevating charge from IPC 304 to 302", "Public places like malls have comprehensive CCTV — request footage immediately"]),
        "tags": json.dumps(["stalking", "murder", "public place", "prior complaint", "delhi", "mall", "premeditation"]),
        "source": "Delhi HC judgment, public record"
    },
    {
        "title": "Bhanwari Devi Murder — Rajasthan Political Scandal",
        "year": 2011, "location": "Jodhpur", "state": "Rajasthan",
        "crime_type": "Murder / Political Cover-up",
        "victim": "Bhanwari Devi, 37, nurse and political activist",
        "accused": "Mahipal Maderna (minister) + accomplices",
        "modus_operandi": "Victim who had a relationship with minister was killed to prevent her from exposing the relationship. Body burned in car.",
        "key_evidence": json.dumps(["CDR showing repeated calls between minister and victim", "Car with burned remains in Jodhpur outskirts", "Accomplice arrested and turned approver", "Sex CD confiscated from minister's home"]),
        "how_solved": "Victim's husband filed complaint. CDR established relationship. Accomplice arrested for unrelated matter and turned approver, revealing the murder plan.",
        "breakthrough": "A CD of victim and minister — found during search in an unrelated case — established motive directly.",
        "outcome": "Maderna arrested, acquitted by sessions court, appeal ongoing",
        "sentence": "Pending",
        "investigation_tips": json.dumps(["Political murder: request CBI transfer immediately — local police face pressure", "CDR analysis between accused and victim is critical to establish relationship and motive", "Approver with firsthand knowledge + corroboration from CDR and forensics = conviction"]),
        "tags": json.dumps(["political murder", "minister", "CD evidence", "CDR", "approver", "Rajasthan", "burnt body"]),
        "source": "Rajasthan HC orders, public record"
    },
    {
        "title": "Dera Sacha Sauda Violence — Panchkula Riots",
        "year": 2017, "location": "Panchkula", "state": "Haryana",
        "crime_type": "Riot / Mass Violence",
        "victim": "36 killed, 250+ injured",
        "accused": "Gurmeet Ram Rahim Singh (cult leader) + followers",
        "modus_operandi": "Upon conviction of cult leader for rape, followers rioted. Arson, shooting, vehicle burning. Cult leader had pre-positioned armed followers.",
        "key_evidence": json.dumps(["Mobile video recordings of rioters by bystanders", "CCTV from Panchkula buildings", "CFSL ballistic analysis of bullets", "Pre-riot communications on FM radio by cult"]),
        "how_solved": "Mass documentation by public via phone cameras identified 600+ rioters. Riot leader convicted on 36 murder charges.",
        "breakthrough": "Thousands of public phone videos submitted to SIT — crowd-sourced evidence identified every key instigator.",
        "outcome": "Ram Rahim convicted for rape (2017) + riot-related murders ongoing",
        "sentence": "20 years for rape. Riot murder trials ongoing.",
        "investigation_tips": json.dumps(["Riot investigation: immediately request all public phone videos via Twitter/Facebook public appeal", "Pre-identify instigators by reviewing leadership structure of organisation", "Mass crowd events: drone footage from nearby buildings/police drones captures identifying shots"]),
        "tags": json.dumps(["riot", "cult", "mass violence", "public video evidence", "crowd sourced", "Haryana", "religious organisation"]),
        "source": "Punjab and Haryana HC, SIT report, public record"
    },
    {
        "title": "Hathras Gang Rape and Death",
        "year": 2020, "location": "Hathras", "state": "Uttar Pradesh",
        "crime_type": "Gang Rape and Murder",
        "victim": "Dalit woman, 19",
        "accused": "4 upper-caste men including Sandeep Singh",
        "modus_operandi": "Victim attacked in field, gang-raped, severe injuries including spinal injury. Died 2 weeks later. Police cremated body at night without family consent.",
        "key_evidence": json.dumps(["Victim's dying declaration", "Medical reports from Aligarh hospital", "Forensic samples destroyed when UP police cremated body", "Video recording by victim's family"]),
        "how_solved": "Partially — dying declaration and family video. But forensic evidence was lost when state police performed midnight cremation without family presence.",
        "breakthrough": "Victim's dying declaration specifically named all four accused.",
        "outcome": "3 convicted (2021), acquitted of gang rape but convicted of culpable homicide",
        "sentence": "Life imprisonment",
        "investigation_tips": json.dumps(["Dying declaration requires magistrate witness — ensure validity procedure", "NEVER allow body disposal before complete forensic sampling, regardless of pressure", "Caste angle in crime: request SC/ST Prevention of Atrocities Act sections proactively", "Midnight cremation = evidence destruction = criminal liability for officers involved"]),
        "tags": json.dumps(["gang rape", "dalit", "dying declaration", "evidence destruction", "midnight cremation", "UP", "caste crime", "landmark"]),
        "source": "Allahabad HC, public record, NHRC report"
    },
    {
        "title": "Sohrabuddin Sheikh Fake Encounter",
        "year": 2005, "location": "Gujarat/Rajasthan", "state": "Gujarat",
        "crime_type": "Extrajudicial Killing / Fake Encounter",
        "victim": "Sohrabuddin Sheikh, Kausar Bi (wife), Tulsiram Prajapati",
        "accused": "Gujarat, Rajasthan police officers (D.G. Vanzara and others)",
        "modus_operandi": "Gangster shot in staged encounter. Wife killed as witness. Third person killed 2 years later as cover-up. CBI investigation found victims were killed in custody.",
        "key_evidence": json.dumps(["Post-mortem reports contradicting encounter story", "CBI analysis of bullet trajectory", "Witness statements from co-accused officers", "Sohrabuddin's phone records before death"]),
        "how_solved": "SC ordered CBI investigation. 38 policemen chargesheeted. All acquitted by special court in 2019 — SC found evidence insufficient.",
        "breakthrough": "Supreme Court suo-motu ordered CBI probe after HC ignored pleas.",
        "outcome": "38 accused police officers acquitted 2019",
        "sentence": "N/A (all acquitted)",
        "investigation_tips": json.dumps(["Encounter deaths: independent post-mortem by civil surgeon + NHRC is mandatory", "SC/NHRC guidelines on encounter deaths must be followed exactly — gap in procedure = inadmissibility", "Officer-on-officer testimony is unreliable in fake encounter cases — need forensic evidence exclusively"]),
        "tags": json.dumps(["fake encounter", "extrajudicial killing", "Gujarat", "CBI", "police accountability", "SC suo motu", "landmark"]),
        "source": "SC judgment, Special CBI court judgment 2019, public record"
    },
    {
        "title": "Telgi Stamp Paper Scam",
        "year": "1993-2003", "location": "Multiple states", "state": "Maharashtra",
        "crime_type": "Fraud / Forgery",
        "victim": "Government of India, public",
        "accused": "Abdul Karim Telgi",
        "modus_operandi": "Forged government stamp papers worth Rs 30,000 crore. Had genuine stamp paper printing machines obtained through bribery. Operated across 12 states.",
        "key_evidence": json.dumps(["Printing machines seized from warehouses", "Forged stamps failed chemical test", "Hawala network mapped through bank transfers", "Witness from government stamp printing department"]),
        "how_solved": "Routine check at market discovered chemically inferior stamp paper. Trail led to warehouse with genuine Security Press equipment — proven to be stolen/cloned.",
        "breakthrough": "A notary's suspicious client brought fake stamp papers to a judge — chemical test revealed fraud.",
        "outcome": "Convicted",
        "sentence": "30 years (died in prison 2017)",
        "investigation_tips": json.dumps(["Document forgery: chemical spectroscopy is conclusive — don't rely on visual inspection alone", "Forgery at scale requires industrial equipment — follow the machinery supply chain", "Hawala networks supporting forged document trade are cross-state — coordinate with ED/NCB"]),
        "tags": json.dumps(["forgery", "stamp paper", "hawala", "Telgi", "Maharashtra", "multi-state", "industrial fraud"]),
        "source": "SC judgment, SIT report, public record"
    },
    {
        "title": "Satyendra Dubey Murder — NHAI Whistleblower",
        "year": 2003, "location": "Gaya", "state": "Bihar",
        "crime_type": "Murder of Whistleblower",
        "victim": "Satyendra Kumar Dubey, 31, IES officer, NHAI",
        "accused": "Highway contractors",
        "modus_operandi": "Dubey wrote to PMO exposing Rs 1000 crore construction fraud. Letter leaked. Shot at night near his quarters.",
        "key_evidence": json.dumps(["PMO letter documenting fraud", "CDR showing calls from contractor to accused killer", "Hired shooter arrested — revealed contractor connection", "Forensic evidence from crime scene"]),
        "how_solved": "Shooter arrested within days. Contractor connection established via CDR. However, main contractor accused were not convicted.",
        "breakthrough": "Shooter was arrested quickly but refused to identify contractor — CDR alone established contractor involvement.",
        "outcome": "Shooter convicted. Main contractor accused — limited action.",
        "sentence": "Life for shooter",
        "investigation_tips": json.dumps(["Whistleblower murder: secure the whistleblower's written complaints as primary evidence of motive", "Contract killers know only their direct employer — go up the chain via CDR and financial records", "Government should have acted on PMO letter — administrative inaction itself is evidence"]),
        "tags": json.dumps(["whistleblower", "murder", "contract killer", "CDR", "Bihar", "road construction fraud", "PMO"]),
        "source": "CBI chargesheet, Patna HC, public record"
    },
    {
        "title": "2G Spectrum Scam",
        "year": "2007-2008", "location": "Delhi", "state": "Delhi",
        "crime_type": "Corruption / Financial Fraud",
        "victim": "Government of India (Rs 1.76 lakh crore alleged loss)",
        "accused": "A. Raja (Telecom Minister) + officials + telecom companies",
        "modus_operandi": "Spectrum licenses allocated at 2001 prices to selected companies using first-come-first-served against rules. Kickbacks allegedly paid through shell companies.",
        "key_evidence": json.dumps(["Audit by CAG documenting Rs 1.76 lakh crore loss", "Telephone intercepts (Niira Radia tapes)", "Shell company fund flows tracked by ED", "Ministry noting files showing deliberate policy violation"]),
        "how_solved": "CAG audit exposed the loss. SC cancelled all 122 licenses. CBI chargesheet based on file notings showing deliberate policy bypass.",
        "breakthrough": "A civil society petition to SC forced a CAG audit — government wouldn't have audited itself.",
        "outcome": "All accused acquitted by Special CBI Court 2017. SC reviewed.",
        "sentence": "N/A (acquitted)",
        "investigation_tips": json.dumps(["Financial scam via government files: compare original policy vs noting in files — deliberate variance = evidence", "Shell company tracing requires cooperation from MCA21 database and ED", "Intercept evidence (tapped phones) requires authorization from Home Secretary — ensure procedure or it's inadmissible"]),
        "tags": json.dumps(["corruption", "spectrum", "financial fraud", "2G", "shell company", "intercept", "CAG", "Delhi"]),
        "source": "SC judgment 2012, Special CBI court judgment 2017, public record"
    },
    {
        "title": "CWG Corruption — Suresh Kalmadi",
        "year": "2008-2010", "location": "Delhi", "state": "Delhi",
        "crime_type": "Corruption / Procurement Fraud",
        "victim": "Government of India (Rs 70,000 crore spent vs Rs 10,000 crore estimated)",
        "accused": "Suresh Kalmadi, OC chairperson + contractors",
        "modus_operandi": "Inflated procurement of equipment (timing devices, scoreboards) by 40x. Kickbacks through foreign companies. Last-minute changes to inflate costs.",
        "key_evidence": json.dumps(["International price comparison showing 40x inflation", "Comparison with similar events overseas", "Vendor selection bypassing tender process", "Wire transfers to offshore accounts"]),
        "how_solved": "CAG audit and CBI investigation. Kalmadi arrested. Chargesheeted for awarding Rs 141 crore contract for timing device at Rs 70 crore above market rate.",
        "breakthrough": "International market price comparison — same Swiss timing device was 40x cheaper when purchased by other countries.",
        "outcome": "Charges dropped by trial court 2019 after prolonged trial",
        "sentence": "N/A (acquitted/charges dropped)",
        "investigation_tips": json.dumps(["Procurement fraud: always conduct international/national price comparison as baseline", "Last-minute contract changes are classic fraud signal — document all amendments", "Sports/event fraud: compare vendor costs with previous editions of same event"]),
        "tags": json.dumps(["corruption", "CWG", "procurement fraud", "price inflation", "Delhi", "government games"]),
        "source": "CAG report, CBI chargesheet, public record"
    },
    {
        "title": "Madhumita Shukla Murder — Political Poet",
        "year": 2003, "location": "Lucknow", "state": "Uttar Pradesh",
        "crime_type": "Murder / Political Crime",
        "victim": "Madhumita Shukla, 24, poet, pregnant",
        "accused": "Amarmani Tripathi (UP Minister), wife",
        "modus_operandi": "Victim had relationship with minister. Shot at home when pregnancy became inconvenient. Body found after 2 days.",
        "key_evidence": json.dumps(["CDR showing 400+ calls between minister and victim", "Minister's aide present at scene", "DNA of foetus — father confirmed via DNA", "Minister's wife's voice on call planning killing"]),
        "how_solved": "Victim's family identified minister as last person in contact. CDR showed 400 calls. DNA of foetus established paternity. Intercepted call between minister and wife planning murder.",
        "breakthrough": "Intercepted call between accused minister and wife explicitly discussing the killing — admitted as evidence.",
        "outcome": "Both convicted",
        "sentence": "Life imprisonment",
        "investigation_tips": json.dumps(["Pregnancy as murder motive: always test for paternity via foetal DNA — establishes relationship motive directly", "Intercepted calls are admissible if authorized by Home Secretary", "Powerful accused: request CBI transfer within 24 hours of arrest"]),
        "tags": json.dumps(["political murder", "minister", "foetal DNA", "intercepted call", "UP", "pregnancy motive", "CDR"]),
        "source": "SC judgment 2010, public record"
    },
    {
        "title": "Bhopal Gas Tragedy Criminal Liability",
        "year": 1984, "location": "Bhopal", "state": "Madhya Pradesh",
        "crime_type": "Industrial Disaster / Criminal Negligence",
        "victim": "15,000+ killed, 500,000+ affected",
        "accused": "Union Carbide India Ltd, Warren Anderson (CEO)",
        "modus_operandi": "Methyl isocyanate gas leak from UCIL plant due to safety lapses. Warning systems disabled, safety protocols ignored, maintenance deferred.",
        "key_evidence": json.dumps(["Plant maintenance records showing disabled safety systems", "Internal UCIL memo on cost-cutting", "Toxicology confirming MIC poisoning in victims", "Safety audit reports ignored by management"]),
        "how_solved": "Not fully — Warren Anderson fled to USA, never extradited. Indian executives convicted of negligence in 2010 — 26 years after disaster.",
        "breakthrough": "Leaked internal safety audit from 1982 showed UCIL knew about 61 hazards — ignored them all.",
        "outcome": "8 Indian executives convicted 2010 for negligence",
        "sentence": "2 years imprisonment (maximum under IPC 304A at the time)",
        "investigation_tips": json.dumps(["Industrial disaster: internal safety audits and maintenance logs are primary evidence — secure before corporate lawyers arrive", "International CEO accused: file Interpol Red Notice immediately and freeze assets", "Industrial negligence cases: CrPC 304 vs 304A distinction — intent to take risk vs recklessness"]),
        "tags": json.dumps(["industrial disaster", "gas tragedy", "Bhopal", "criminal negligence", "MNC", "Interpol", "landmark"]),
        "source": "Bhopal Sessions Court 2010, public record"
    },
    {
        "title": "Bilkis Bano Gang Rape — 2002 Gujarat Riots",
        "year": 2002, "location": "Limkheda", "state": "Gujarat",
        "crime_type": "Gang Rape / Murder (Communal Violence)",
        "victim": "Bilkis Bano (19, pregnant) + 14 family members killed",
        "accused": "12 convicted (Gujarat policemen + civilians)",
        "modus_operandi": "During 2002 Gujarat riots, mob attacked refugee family. Bilkis raped by 12 men. 14 family members including her 3-year-old daughter killed.",
        "key_evidence": json.dumps(["Victim's testimony (consistent across multiple re-tellings)", "DNA from rape kit", "Exhumation of 14 bodies 2 years later", "CBI investigation ordered by SC"]),
        "how_solved": "Victim filed complaint but local police created false FIR. SC ordered CBI probe. CBI exhumed bodies, found DNA, secured conviction.",
        "breakthrough": "Bilkis's consistent, detailed testimony withstood 20 years of legal challenges — human testimony can outlast political pressure.",
        "outcome": "12 convicted for life. Controversial remission in 2022 reversed by SC 2024.",
        "sentence": "Life imprisonment (remission cancelled by SC 2024)",
        "investigation_tips": json.dumps(["Communal violence: record victim testimony IMMEDIATELY before community pressure silences them", "Exhumation is valid years later — DNA survives in bones", "Local police false FIR: victim can approach HC/SC directly with supporting evidence"]),
        "tags": json.dumps(["communal violence", "gang rape", "Gujarat", "CBI", "exhumation", "DNA", "SC intervention", "landmark"]),
        "source": "Supreme Court judgment 2019 and 2024, public record"
    },
    {
        "title": "Nambi Narayanan Espionage Case — Wrongful Prosecution",
        "year": 1994, "location": "Thiruvananthapuram", "state": "Kerala",
        "crime_type": "Wrongful Prosecution / False Case",
        "victim": "Nambi Narayanan, ISRO scientist (wrongly accused)",
        "accused": "Kerala Police (wrongful prosecution)",
        "modus_operandi": "ISRO scientist falsely accused of passing cryogenic rocket secrets to Pakistan. Police extracted confessions under torture. Case later found to be fabricated.",
        "key_evidence": json.dumps(["Maldivian woman's false testimony later recanted", "CBI found no evidence of secrets transfer", "SC found police fabricated entire case", "Medical evidence of custodial torture"]),
        "how_solved": "CBI investigation cleared Narayanan. SC awarded compensation in 2018. SC ordered inquiry into conspiracy to frame him.",
        "breakthrough": "CBI found the 'secret documents' never left India and were not actually classified.",
        "outcome": "Narayanan exonerated. SC awarded Rs 50 lakh compensation. SC ordered inquiry into police conspiracy.",
        "sentence": "N/A (wrongful prosecution case)",
        "investigation_tips": json.dumps(["Espionage cases: verify classification of documents FIRST before arresting — wrong classification = wrongful arrest", "Custodial confession is invalid if there is medical evidence of torture", "High-profile arrests need approval at IG level minimum — individual SHO cannot arrest ISRO scientists"]),
        "tags": json.dumps(["wrongful prosecution", "ISRO", "espionage", "CBI", "Kerala", "police misconduct", "SC compensation", "landmark"]),
        "source": "SC judgment 2018, CBI closure report, public record"
    },

    # ── CYBER / FINANCIAL CRIMES ──────────────────────────────────────────────
    {
        "title": "Punjab National Bank Fraud — Nirav Modi",
        "year": "2011-2018", "location": "Mumbai", "state": "Maharashtra",
        "crime_type": "Bank Fraud / Money Laundering",
        "victim": "Punjab National Bank, Rs 14,000 crore",
        "accused": "Nirav Modi, Mehul Choksi, bank officials",
        "modus_operandi": "Fraudulent Letters of Undertaking (LoUs) issued by PNB Brady branch officials. Used to obtain loans from overseas PNB branches. Loans never repaid. Officials bypassed SWIFT-CBS integration.",
        "key_evidence": json.dumps(["Fraudulent LoU documents", "SWIFT messages not recorded in CBS (core banking)", "Offshore shell company transactions", "Bank official confessional statements"]),
        "how_solved": "New bank official noticed SWIFT messages not in CBS. PNB filed complaint. CBI + ED launched parallel investigation. Nirav Modi fled to UK, extradition battle ongoing.",
        "breakthrough": "A single vigilant bank official noticed a SWIFT message not entered in CBS — technological gap exposed the fraud.",
        "outcome": "Nirav Modi arrested in UK 2019, extradition ordered 2021. Mehul Choksi in Antigua.",
        "sentence": "Pending extradition",
        "investigation_tips": json.dumps(["Bank fraud: always cross-check SWIFT messages with CBS entries — any gap is suspicious", "LoU fraud is enabled by single-person authorization — flag any LoU above threshold issued without dual control", "Extradition process: file INTERPOL Red Notice + chargesheet simultaneously to block asset movement"]),
        "tags": json.dumps(["bank fraud", "PNB", "LoU", "SWIFT", "money laundering", "extradition", "Nirav Modi", "Mumbai"]),
        "source": "CBI chargesheet, ED attachment orders, UK court extradition judgment"
    },
    {
        "title": "Rose Valley Chit Fund Scam",
        "year": "2000-2013", "location": "Kolkata", "state": "West Bengal",
        "crime_type": "Ponzi / Chit Fund Fraud",
        "victim": "17 lakh investors, Rs 17,000 crore",
        "accused": "Gautam Kundu, founder",
        "modus_operandi": "Promised 12-15% returns through hotels, resorts, multiplex. Used new investor money to pay old. Collapsed when RBI intervened.",
        "key_evidence": json.dumps(["RBI inspection report identifying Ponzi structure", "Company balance sheets showing payments from deposits not profits", "ED attachment of 90 hotels and properties", "Bank statements of 17 lakh investors"]),
        "how_solved": "RBI raised red flag after routine inspection. ED froze assets. SIT arrested Kundu. Investors mobilised for evidence. Properties auction ongoing.",
        "breakthrough": "RBI inspection report documented cash flow model proving Ponzi structure mathematically.",
        "outcome": "Convicted",
        "sentence": "3 years (extended appeals)",
        "investigation_tips": json.dumps(["Ponzi detection: payment to investors > declared profit = mathematically impossible legitimately", "Chit fund scams: victims hold receipts — collect all and build investor list before accused destroys records", "RBI/SEBI reports are admissible documentary evidence in financial crime trials"]),
        "tags": json.dumps(["ponzi", "chit fund", "West Bengal", "RBI", "ED", "real estate", "investor fraud"]),
        "source": "ED chargesheet, Calcutta HC, public record"
    },
    {
        "title": "OLX Scam — Army Impersonation Fraud",
        "year": "2019-2022", "location": "Multiple cities", "state": "Rajasthan",
        "crime_type": "Online Fraud",
        "victim": "10,000+ victims, Rs 200 crore estimated",
        "accused": "Bharatpur gang (Rajasthan)",
        "modus_operandi": "Accused posed as army officers on OLX selling items (bikes, cars, furniture). Asked for advance payment before delivery. No item delivered. UPI accounts used.",
        "key_evidence": json.dumps(["OLX listings with military imagery", "UPI account holder details", "Phone numbers traced to Bharatpur cluster", "Victim screenshots of WhatsApp conversations"]),
        "how_solved": "Multiple police forces cooperated. Bharatpur police raided after pattern emerged across states. Mobile number cluster analysis showed same 200 numbers used in 10,000 cases.",
        "breakthrough": "50 victims filed complaints in one day — police ran mobile number cluster analysis and found all calls from 200 numbers in Bharatpur.",
        "outcome": "200+ arrested",
        "sentence": "Various 3-7 year terms",
        "investigation_tips": json.dumps(["Online fraud clusters: map phone numbers spatially — 50+ numbers from same 10km radius = organized gang", "Military impersonation: report to respective army unit — military police has own investigation jurisdiction", "UPI account holder is traceable via NPCI — always file with cyber cell to get UPI holder details"]),
        "tags": json.dumps(["online fraud", "OLX", "military impersonation", "UPI", "Bharatpur gang", "Rajasthan", "cluster analysis"]),
        "source": "Cyber police press releases, public record"
    },
    {
        "title": "Narada Sting — Bengal Politicians Bribery",
        "year": 2016, "location": "Kolkata", "state": "West Bengal",
        "crime_type": "Corruption / Bribery",
        "victim": "Government integrity",
        "accused": "Trinamool Congress politicians, IPS officer",
        "modus_operandi": "Journalist posed as businessman offering bribes to politicians for favours. Video-recorded all transactions. Published footage showing 12 politicians accepting cash.",
        "key_evidence": json.dumps(["Sting video recordings (2 years undercover)", "Currency with serial numbers pre-recorded", "Signed acknowledgments by some accused", "CBI expert confirmed authenticity of videos"]),
        "how_solved": "Videos published 2016, CBI took cognizance. Arrests 2021.",
        "breakthrough": "Pre-recorded currency serial numbers — money could not be denied as bribe.",
        "outcome": "CBI chargesheeted 13 accused. Trial ongoing.",
        "sentence": "Trial ongoing (2024)",
        "investigation_tips": json.dumps(["Sting evidence: pre-record serial numbers of currency BEFORE sting for conclusive evidence", "Sting videos must have continuous timestamp overlay — any gap creates defense argument", "Video authentication: CFSL forensic authentication is mandatory for sting videos in court"]),
        "tags": json.dumps(["sting operation", "bribery", "TMC", "West Bengal", "CBI", "video evidence", "politicians", "undercover"]),
        "source": "CBI chargesheet, Calcutta HC, public record"
    },
    {
        "title": "Sukinda Chromite Mine Deaths — Odisha",
        "year": "2000s", "location": "Sukinda", "state": "Odisha",
        "crime_type": "Environmental Crime / Industrial Manslaughter",
        "victim": "Thousands of villagers from hexavalent chromium poisoning",
        "accused": "TISCO, IMFA and other mining companies",
        "modus_operandi": "Waste water from chromite mines contaminated drinking water with hexavalent chromium (Cr-VI), a carcinogen. Companies knew but continued discharge.",
        "key_evidence": json.dumps(["Water samples with Cr-VI exceeding WHO limits by 25x", "Company internal reports acknowledging contamination", "Medical records of 30,000+ cancer and kidney patients", "NEERI environmental audit"]),
        "how_solved": "Environmental activists collected water samples. NEERI confirmed Sukinda valley had highest Cr-VI contamination in world. PIL filed in HC.",
        "breakthrough": "NGO collected 500 water samples and had them lab-tested — undeniable scientific evidence.",
        "outcome": "Partial remediation ordered. Criminal cases pending for 20+ years.",
        "sentence": "N/A (pending)",
        "investigation_tips": json.dumps(["Environmental crime: collect water/soil samples from multiple points — pattern of contamination proves systematic discharge", "Independent NABL-accredited lab certification is required — company-friendly labs are inadmissible", "Medical data from local hospitals is admissible to prove harm causation"]),
        "tags": json.dumps(["environmental crime", "mining", "chromium", "industrial", "Odisha", "NGO evidence", "PIL", "carcinogen"]),
        "source": "Odisha HC PIL orders, NEERI reports, public record"
    },
    {
        "title": "Serial Killer Cyanide Mohan — Karnataka",
        "year": "2005-2009", "location": "Bengaluru and districts", "state": "Karnataka",
        "crime_type": "Serial Murder by Poisoning",
        "victim": "6 women (all widows/single women seeking loans)",
        "accused": "Mohan Kumar alias Cyanide Mohan",
        "modus_operandi": "Posed as government employee. Lured widows seeking loans with marriage promise. Married briefly. Fed cyanide capsule disguised as contraceptive. Stole gold.",
        "key_evidence": json.dumps(["Cyanide in victims' viscera (postmortem)", "Marriage certificates in different names", "Stolen gold traced to jewellery shops", "Victim families identified accused from photo lineup"]),
        "how_solved": "One victim survived, identified accused. Pattern emerged linking 5 deaths across districts as same MO. Accused identified, arrested. Confirmed 6 murders.",
        "breakthrough": "Surviving victim gave exact description — composite sketch led to arrest within 2 weeks.",
        "outcome": "Convicted in all 6 murders",
        "sentence": "Death sentence (commuted)",
        "investigation_tips": json.dumps(["Cyanide poisoning: appears as cardiac arrest — always test viscera for cyanide in sudden deaths of healthy individuals", "Serial matrimonial fraud: always verify marriage certificates across districts", "Surviving victim in serial case = most critical asset — provide protection immediately"]),
        "tags": json.dumps(["serial killer", "cyanide", "poison", "matrimonial fraud", "Karnataka", "widows", "gold theft", "composite sketch"]),
        "source": "Karnataka HC, public judgment"
    },
    {
        "title": "Bengaluru Pub Attack — Sri Ram Sene",
        "year": 2009, "location": "Mangaluru", "state": "Karnataka",
        "crime_type": "Moral Policing / Assault",
        "victim": "Young women at Amnesia pub",
        "accused": "Pramod Muthalik, Sri Ram Sene members",
        "modus_operandi": "Political group raided pub, attacked women celebrating, dragged them out. Accused of moral policing. Caught on camera.",
        "key_evidence": json.dumps(["Multiple CCTV and media video footage from inside pub", "Victim testimonies", "Accused identified by name from SRS membership list", "Pramod Muthalik arrested same day"]),
        "how_solved": "Entire attack captured on media cameras (journalists were tipped off). Accused identified from footage. All arrested within 24 hours. Case fast-tracked.",
        "breakthrough": "Media footage was so comprehensive that no accused could deny presence.",
        "outcome": "Acquitted by trial court — victims turned hostile. Accused released on bail.",
        "sentence": "Acquitted 2012",
        "investigation_tips": json.dumps(["Public violence with media footage: preserve ALL media recordings before edits — originals from camera cards", "Witness hostility in moral policing cases is common — focus on CCTV/media as primary evidence", "Document injuries of victims within 24 hours with medical report"]),
        "tags": json.dumps(["moral policing", "assault", "pub attack", "media evidence", "Karnataka", "Mangaluru", "acquittal"]),
        "source": "Karnataka HC, public record"
    },
    {
        "title": "Lavanya Caste Discrimination Suicide — Tamil Nadu",
        "year": 2022, "location": "Thanjavur", "state": "Tamil Nadu",
        "crime_type": "Abetment of Suicide / Caste Harassment",
        "victim": "Lavanya J., 17, class 12 student, Dalit",
        "accused": "School principal, nuns (religious conversion pressure alleged)",
        "modus_operandi": "Student alleged she was forced to do cleaning work due to caste, pressured to convert. Left video will before consuming poison in school toilet.",
        "key_evidence": json.dumps(["Dying video declaration on phone", "School duty register showing cleaning assigned only to SC/ST students", "Prior complaint to school management", "SC/ST Prevention of Atrocities Act provisions"]),
        "how_solved": "Video testament went viral. CBI investigation ordered by Madras HC. School records showed discriminatory work assignment pattern.",
        "breakthrough": "Video testament — victim recorded herself explaining the harassment while dying.",
        "outcome": "3 school officials arrested. Trial ongoing.",
        "sentence": "Trial ongoing",
        "investigation_tips": json.dumps(["Caste-based institutional harassment: audit duty rosters for discriminatory assignment patterns", "Video testament is dying declaration if victim dies — high evidentiary value", "SC/ST Atrocities Act: file under specific sections — caste must be motive, not incidental"]),
        "tags": json.dumps(["caste harassment", "Dalit", "suicide", "school", "video testament", "SC/ST Act", "Tamil Nadu", "dying declaration"]),
        "source": "Madras HC orders, CBI probe order, public record"
    },
    {
        "title": "Hashimpura Massacre",
        "year": 1987, "location": "Meerut", "state": "Uttar Pradesh",
        "crime_type": "Custodial Killing / Communal Violence",
        "victim": "42 Muslim men killed in custody",
        "accused": "Provincial Armed Constabulary (PAC) personnel",
        "modus_operandi": "During Meerut riots, PAC took 42 Muslim men into custody. Shot them and dumped in canal. Claimed they tried to escape.",
        "key_evidence": json.dumps(["Survivor testimony (5 survived by playing dead)", "Bodies recovered from Murad Nagar canal", "PAC truck number linked to accused unit", "Ballistic analysis — shots at close range contradicting escape story"]),
        "how_solved": "Survivors filed FIR. Bodies found in canal. Ballistics proved point-blank execution, not escape shooting. Case took 28 years.",
        "breakthrough": "5 survivors played dead — their testimony and wounds proved execution, not encounter.",
        "outcome": "16 PAC personnel convicted 2015 (28 years later). HC enhanced sentence 2018.",
        "sentence": "Life imprisonment for 16 PAC personnel",
        "investigation_tips": json.dumps(["Custodial killing: survivor testimony is most powerful — protect survivors immediately", "Ballistics: entry wound angle and distance proves execution vs encounter — always document", "Custodial deaths: independent medical exam mandatory within 24 hours of recovery"]),
        "tags": json.dumps(["custodial killing", "PAC", "communal", "UP", "Muslim", "survivors testimony", "landmark", "delayed justice", "28 years"]),
        "source": "Delhi HC judgment 2018, public record"
    },
]

def seed():
    conn = sqlite3.connect(DB_PATH)
    conn.executescript(SCHEMA)

    # Clear existing data for idempotent re-runs
    conn.execute("DELETE FROM solved_cases")
    conn.execute("INSERT INTO solved_cases_fts(solved_cases_fts) VALUES('delete-all')")

    for case in CASES:
        conn.execute("""
            INSERT INTO solved_cases
              (title, year, location, state, crime_type, victim, accused,
               modus_operandi, key_evidence, how_solved, breakthrough,
               outcome, sentence, investigation_tips, tags, source)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            case["title"], case.get("year"), case.get("location"), case.get("state"),
            case.get("crime_type"), case.get("victim"), case.get("accused"),
            case.get("modus_operandi"), case.get("key_evidence"), case.get("how_solved"),
            case.get("breakthrough"), case.get("outcome"), case.get("sentence"),
            case.get("investigation_tips"), case.get("tags"), case.get("source"),
        ))

    conn.commit()
    # Rebuild FTS index
    conn.execute("INSERT INTO solved_cases_fts(solved_cases_fts) VALUES('rebuild')")
    conn.commit()
    count = conn.execute("SELECT COUNT(*) FROM solved_cases").fetchone()[0]
    print(f"[OK] Seeded {count} cases into {DB_PATH}")

    # Test FTS
    results = conn.execute(
        "SELECT title FROM solved_cases_fts WHERE solved_cases_fts MATCH 'DNA murder' LIMIT 3"
    ).fetchall()
    print(f"[OK] FTS test 'DNA murder' -> {[r[0] for r in results]}")
    conn.close()

if __name__ == "__main__":
    seed()
