"""Karnataka districts, police station templates, and crime head reference data."""

KARNATAKA_DISTRICTS = [
    {"name": "Bengaluru Urban", "name_kn": "ಬೆಂಗಳೂರು ನಗರ", "lat": 12.9716, "lon": 77.5946, "pop": 9620551, "zone": "South"},
    {"name": "Bengaluru Rural", "name_kn": "ಬೆಂಗಳೂರು ಗ್ರಾಮ", "lat": 13.2257, "lon": 77.5750, "pop": 990922, "zone": "South"},
    {"name": "Mysuru", "name_kn": "ಮೈಸೂರು", "lat": 12.2958, "lon": 76.6394, "pop": 1281769, "zone": "South"},
    {"name": "Belagavi", "name_kn": "ಬೆಳಗಾವಿ", "lat": 15.8497, "lon": 74.4977, "pop": 2036482, "zone": "North"},
    {"name": "Kalaburagi", "name_kn": "ಕಲಬುರಗಿ", "lat": 17.3297, "lon": 76.8343, "pop": 2564892, "zone": "North"},
    {"name": "Dakshina Kannada", "name_kn": "ದಕ್ಷಿಣ ಕನ್ನಡ", "lat": 12.9141, "lon": 74.8560, "pop": 2089649, "zone": "Coastal"},
    {"name": "Udupi", "name_kn": "ಉಡುಪಿ", "lat": 13.3409, "lon": 74.7421, "pop": 1177361, "zone": "Coastal"},
    {"name": "Hassan", "name_kn": "ಹಾಸನ", "lat": 13.0072, "lon": 76.0962, "pop": 1776421, "zone": "South"},
    {"name": "Shivamogga", "name_kn": "ಶಿವಮೊಗ್ಗ", "lat": 13.9299, "lon": 75.5681, "pop": 1752753, "zone": "Malnad"},
    {"name": "Tumakuru", "name_kn": "ತುಮಕೂರು", "lat": 13.3409, "lon": 77.1010, "pop": 2678980, "zone": "South"},
    {"name": "Ballari", "name_kn": "ಬಳ್ಳಾರಿ", "lat": 15.1394, "lon": 76.9214, "pop": 2452595, "zone": "North"},
    {"name": "Vijayapura", "name_kn": "ವಿಜಯಪುರ", "lat": 16.8302, "lon": 75.7100, "pop": 2177331, "zone": "North"},
    {"name": "Raichur", "name_kn": "ರಾಯಚೂರು", "lat": 16.2076, "lon": 77.3463, "pop": 1928812, "zone": "North"},
    {"name": "Dharwad", "name_kn": "ಧಾರವಾಡ", "lat": 15.4589, "lon": 75.0078, "pop": 1847023, "zone": "North"},
    {"name": "Gadag", "name_kn": "ಗadag", "lat": 15.4167, "lon": 75.6167, "pop": 1067179, "zone": "North"},
    {"name": "Haveri", "name_kn": "ಹaveri", "lat": 14.7951, "lon": 75.3990, "pop": 1598506, "zone": "North"},
    {"name": "Chitradurga", "name_kn": "ಚitradurga", "lat": 14.2226, "lon": 76.3980, "pop": 1659456, "zone": "South"},
    {"name": "Chikkamagaluru", "name_kn": "ಚikkamagaluru", "lat": 13.3161, "lon": 75.7720, "pop": 1137961, "zone": "Malnad"},
    {"name": "Kodagu", "name_kn": "ಕodagu", "lat": 12.4244, "lon": 75.7382, "pop": 554519, "zone": "Malnad"},
    {"name": "Mandya", "name_kn": "ಮandya", "lat": 12.5218, "lon": 76.8951, "pop": 1805769, "zone": "South"},
    {"name": "Kolar", "name_kn": "ಕolar", "lat": 13.1360, "lon": 78.1292, "pop": 1536401, "zone": "South"},
    {"name": "Chikkaballapur", "name_kn": "ಚikkaballapur", "lat": 13.4355, "lon": 77.7315, "pop": 1255104, "zone": "South"},
    {"name": "Ramanagara", "name_kn": "ರamanagara", "lat": 12.7235, "lon": 77.2807, "pop": 1082739, "zone": "South"},
    {"name": "Yadgir", "name_kn": "ಯadgir", "lat": 16.7704, "lon": 77.1376, "pop": 1174272, "zone": "North"},
    {"name": "Bidar", "name_kn": "ಬidar", "lat": 17.9133, "lon": 77.5300, "pop": 1703300, "zone": "North"},
    {"name": "Koppal", "name_kn": "ಕoppal", "lat": 15.3500, "lon": 76.1500, "pop": 1388727, "zone": "North"},
    {"name": "Bagalkot", "name_kn": "ಬagalkot", "lat": 16.1864, "lon": 75.6960, "pop": 1886334, "zone": "North"},
    {"name": "Uttara Kannada", "name_kn": "ಉttara Kannada", "lat": 14.7936, "lon": 74.6869, "pop": 1437169, "zone": "Coastal"},
    {"name": "Davanagere", "name_kn": "ದavanagere", "lat": 14.4644, "lon": 75.9218, "pop": 1945497, "zone": "Malnad"},
    {"name": "Vijayanagara", "name_kn": "ವijayanagara", "lat": 15.3350, "lon": 76.4600, "pop": 1356714, "zone": "North"},
    {"name": "Chamarajanagar", "name_kn": "ಚamarajanagar", "lat": 11.9261, "lon": 76.9437, "pop": 1020962, "zone": "South"},
]

CRIME_HEADS = [
    {"name": "Theft", "category": "IPC", "ipc_section": "379", "severity": "medium"},
    {"name": "House Breaking & Theft", "category": "IPC", "ipc_section": "457", "severity": "high"},
    {"name": "Robbery", "category": "IPC", "ipc_section": "392", "severity": "high"},
    {"name": "Dacoity", "category": "IPC", "ipc_section": "395", "severity": "critical"},
    {"name": "Murder", "category": "IPC", "ipc_section": "302", "severity": "critical"},
    {"name": "Attempt to Murder", "category": "IPC", "ipc_section": "307", "severity": "critical"},
    {"name": "Culpable Homicide", "category": "IPC", "ipc_section": "304", "severity": "critical"},
    {"name": "Rape", "category": "IPC", "ipc_section": "376", "severity": "critical"},
    {"name": "Assault on Women", "category": "IPC", "ipc_section": "354", "severity": "high"},
    {"name": "Sexual Harassment", "category": "IPC", "ipc_section": "354A", "severity": "high"},
    {"name": "Kidnapping & Abduction", "category": "IPC", "ipc_section": "363", "severity": "high"},
    {"name": "Cheating & Fraud", "category": "IPC", "ipc_section": "420", "severity": "medium"},
    {"name": "Criminal Breach of Trust", "category": "IPC", "ipc_section": "406", "severity": "medium"},
    {"name": "Forgery", "category": "IPC", "ipc_section": "465", "severity": "medium"},
    {"name": "Counterfeiting", "category": "IPC", "ipc_section": "489A", "severity": "high"},
    {"name": "Cyber Crime - Online Fraud", "category": "BNS", "ipc_section": "318", "severity": "high"},
    {"name": "Cyber Crime - Identity Theft", "category": "BNS", "ipc_section": "319", "severity": "high"},
    {"name": "Cyber Crime - Hacking", "category": "BNS", "ipc_section": "320", "severity": "high"},
    {"name": "Cyber Crime - Phishing", "category": "BNS", "ipc_section": "321", "severity": "medium"},
    {"name": "Dowry Death", "category": "SLL", "ipc_section": "304B", "severity": "critical"},
    {"name": "Dowry Prohibition Act", "category": "SLL", "ipc_section": "DP Act", "severity": "high"},
    {"name": "POCSO Act", "category": "SLL", "ipc_section": "POCSO", "severity": "critical"},
    {"name": "Domestic Violence", "category": "SLL", "ipc_section": "DV Act", "severity": "high"},
    {"name": "NDPS Act", "category": "SLL", "ipc_section": "NDPS", "severity": "high"},
    {"name": "Arms Act", "category": "SLL", "ipc_section": "Arms Act", "severity": "high"},
    {"name": "Riots", "category": "IPC", "ipc_section": "147", "severity": "high"},
    {"name": "Hurt/Grievous Hurt", "category": "IPC", "ipc_section": "325", "severity": "medium"},
    {"name": "Criminal Trespass", "category": "IPC", "ipc_section": "447", "severity": "low"},
    {"name": "Mischief", "category": "IPC", "ipc_section": "425", "severity": "low"},
    {"name": "Extortion", "category": "IPC", "ipc_section": "384", "severity": "high"},
    {"name": "Criminal Intimidation", "category": "IPC", "ipc_section": "506", "severity": "medium"},
    {"name": "Missing Person", "category": "IPC", "ipc_section": "N/A", "severity": "medium"},
    {"name": "Road Accident Death", "category": "IPC", "ipc_section": "304A", "severity": "high"},
    {"name": "Immoral Traffic Act", "category": "SLL", "ipc_section": "ITPA", "severity": "high"},
    {"name": "SC/ST Atrocities Act", "category": "SLL", "ipc_section": "SC/ST Act", "severity": "high"},
]

CRIME_WEIGHTS = {
    "Theft": 18, "House Breaking & Theft": 8, "Robbery": 4, "Murder": 1.5,
    "Attempt to Murder": 2, "Rape": 2, "Assault on Women": 5,
    "Sexual Harassment": 3, "Kidnapping & Abduction": 2, "Cheating & Fraud": 10,
    "Criminal Breach of Trust": 4, "Forgery": 3, "Cyber Crime - Online Fraud": 8,
    "Cyber Crime - Identity Theft": 4, "Cyber Crime - Hacking": 3,
    "Cyber Crime - Phishing": 5, "Dowry Prohibition Act": 3, "POCSO Act": 4,
    "Domestic Violence": 3, "NDPS Act": 3, "Arms Act": 2, "Riots": 2,
    "Hurt/Grievous Hurt": 6, "Criminal Trespass": 4, "Mischief": 3,
    "Extortion": 2, "Missing Person": 2, "Road Accident Death": 2,
    "SC/ST Atrocities Act": 1.5, "Dacoity": 0.5, "Counterfeiting": 1,
    "Dowry Death": 0.8, "Immoral Traffic Act": 1, "Criminal Intimidation": 2,
    "Culpable Homicide": 0.5,
}

FIR_STATUSES = ["registered", "under_investigation", "chargesheeted", "closed", "pending_trial"]
CRIMINAL_STATUSES = ["absconding", "arrested", "on_bail", "convicted", "acquitted"]

STATION_PREFIXES = [
    "City", "Town", "Rural", "Traffic", "Women", "Cyber", "Economic Offences",
    "North", "South", "East", "West", "Central", "Market", "Railway",
]
